csa_guzzle:
    profiler: "%kernel.debug%"
    logger: true
    clients:
        mailjet_api:
            config:
                base_uri: 'https://api.mailjet.com/v3/'
                timeout: 2.0
                headers:
                    Content-Type: 'application/json'

        google_charts_api:
            config:
                base_uri: 'https://chart.googleapis.com'
                timeout: 2.0

        google_maps_static_api:
            config:
                base_uri: 'https://maps.googleapis.com'
                timeout: 2.0

        facebook_graph_api:
            config:
                base_uri: 'https://graph.facebook.com'
                timeout: 2.0

        mailchimp_api:
            config:
                base_uri: 'https://us16.api.mailchimp.com'
                timeout: 60.0
                headers:
                    Content-Type: 'application/json'
                    Authorization: 'Bearer %env(MAILCHIMP_API_KEY)%'
