framework:
    secret: '%env(APP_SECRET)%'
    templating:
        engines: ['twig']
    session:
        name: enmarche
        handler_id: snc_redis.session.handler
    cache:
        app: cache.adapter.doctrine
        default_doctrine_provider: cache.redis_doctrine_provider
        pools:
            app.cache.redirection:
                adapter: cache.adapter.doctrine
            app.cache.republican_silence: ~
    translator:      { fallbacks: ["%locale%"], paths: ["%kernel.project_dir%/translations"] }
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
