lexik_paybox:
    parameters:
        production:  "%env(bool:PAYBOX_PRODUCTION)%"
        site:        "%env(PAYBOX_SITE)%"
        rank:        "%env(PAYBOX_RANK)%"
        login:       "%env(PAYBOX_IDENTIFIER)%"
        hmac:
            key:     "%env(PAYBOX_KEY)%"
