old_sound_rabbit_mq:
    connections:
        default:
            host: "%env(RABBITMQ_HOST)%"
            port: "%env(RABBITMQ_PORT)%"
            user: "%env(RABBITMQ_USER)%"
            password: "%env(RABBITMQ_PASSWORD)%"
            vhost: '/'
            lazy: false
            connection_timeout: 10
            read_write_timeout: 10
            heartbeat: 5

    producers:
        mailer_campaign:
            connection:       default
            exchange_options: { name: 'mailer-delayed-campaign', type: direct }
            class:            AppBundle\Producer\MailerProducer

        mailer_transactional:
            connection:       default
            exchange_options: { name: 'mailer-delayed-transactional', type: direct }
            class:            AppBundle\Producer\MailerProducer

        referent_message_dispatcher:
            connection:       default
            exchange_options: { name: 'referent-message-dispatcher', type: direct }
            class:            AppBundle\Producer\ReferentMessageDispatcherProducer

        deputy_message_dispatcher:
            connection:       default
            exchange_options: { name: 'deputy-message-dispatcher', type: direct }
            class:            AppBundle\Producer\DeputyMessageDispatcherProducer

        project_citizen_creation_notification:
            connection: default
            exchange_options: { name: 'project_citizen_creation_notification', type: direct }

        sync_api:
            connection: default
            exchange_options: { name: 'api', type: topic }

    consumers:
        mailer_campaign:
            connection:        default
            exchange_options:  { name: 'mailer-delayed-campaign', type: direct }
            queue_options:     { name: 'mailer-delayed-campaign', durable: false }
            callback:          AppBundle\Consumer\CampaignMailerConsumer
            qos_options:       { prefetch_size: 0, prefetch_count: 1, global: false }

        mailer_transactional:
            connection:        default
            exchange_options:  { name: 'mailer-delayed-transactional', type: direct }
            queue_options:     { name: 'mailer-delayed-transactional', durable: false }
            callback:          AppBundle\Consumer\TransactionalMailerConsumer
            qos_options:       { prefetch_size: 0, prefetch_count: 1, global: false }

        referent_message_dispatcher:
            connection:        default
            exchange_options:  { name: 'referent-message-dispatcher', type: direct }
            queue_options:     { name: 'referent-message-dispatcher', durable: false }
            callback:          AppBundle\Consumer\ReferentMessageDispatcherConsumer
            qos_options:       { prefetch_size: 0, prefetch_count: 1, global: false }

        deputy_message_dispatcher:
            connection:        default
            exchange_options:  { name: 'deputy-message-dispatcher', type: direct }
            queue_options:     { name: 'deputy-message-dispatcher', durable: false }
            callback:          AppBundle\Consumer\DeputyMessageDispatcherConsumer
            qos_options:       { prefetch_size: 0, prefetch_count: 1, global: false }

        project_citizen_creation_notification:
            connection:        default
            exchange_options:  { name: 'project_citizen_creation_notification', type: direct }
            queue_options:     { name: 'project_citizen_creation_notification', durable: false }
            callback:          AppBundle\Consumer\ProjectCitizenCreationNotificationConsumer
            qos_options:       { prefetch_size: 0, prefetch_count: 1, global: false }

        mailer:
            connection:        default
            exchange_options:  { name: 'mails', type: direct }
            queue_options:     { name: 'mails', durable: false, routing_keys: [mailer.scheduled_mail] }
            callback:          AppBundle\Consumer\MailerConsumer
            qos_options:       { prefetch_size: 0, prefetch_count: 1, global: false }
